name: hot_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.2

dev_dependencies:
  lints: ^5.0.0
  mason: ^0.1.1
  test: ^1.24.0

dependencies:
  args: ^2.7.0
  mason_cli: ^0.1.2
  path: ^1.9.1
